services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    # For development, add --reload for instant code changes
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt 
        - action: rebuild
          path: ./backend/Dockerfile
        - action: sync
          path: ./backend/src
          target: /app/src # Change /app/src to your container's source code path

  frontend:
    build:
      context: ./static_html
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python -m http.server 8000